/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaminasPackage;

import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class UIAplicacion extends javax.swing.JFrame {

    private static List<String> elementsToShow = new ArrayList();
    private static List<String> elementsToShowNumbers = new ArrayList();

    public UIAplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        pnInicio = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnNormal = new javax.swing.JButton();
        btnDificil = new javax.swing.JButton();
        lblSeleccionar = new javax.swing.JLabel();
        pnJuego5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblquatity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnPrincipal.setBackground(new java.awt.Color(51, 102, 255));
        pnPrincipal.setLayout(new java.awt.CardLayout());

        pnInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setText("Buscaminas");
        pnInicio.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        btnNormal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNormal.setText("Normal");
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });
        pnInicio.add(btnNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, 70));

        btnDificil.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDificil.setText("Difìcil");
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });
        pnInicio.add(btnDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 150, 70));

        lblSeleccionar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSeleccionar.setText("Seleccione dificultad");
        pnInicio.add(lblSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        pnPrincipal.add(pnInicio, "card2");

        pnJuego5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscaminasPackage/min.png"))); // NOI18N
        pnJuego5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        lblquatity.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblquatity.setText("5");
        pnJuego5.add(lblquatity, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        pnPrincipal.add(pnJuego5, "card3");

        getContentPane().add(pnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Map<String, JButton> buttonMap = new HashMap<String, JButton>();

    private void initpnJuego5(int psize) {
        //comment
        int posx = 10;
        int posy = 10;
        int length;
        String name;
        if (psize == 5) {
            length = 60;
        } else {
            length = 40;
        }
        for (int i = 0; i <= psize; i++) {
            for (int j = 0; j <= psize; j++) {
                JButton btn = new JButton();
                name = "b" + i + j;
                btn.setName(name);
                btn.setBackground(new java.awt.Color(255, 153, 51));
                btn.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        buttonClicked(evt);
                    }
                });
                pnJuego5.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(posx, posy, length, length));
                buttonMap.put(name, btn);
                posx += length;
            }
            posx = 10;
            posy += length;
        }
        lblquatity.setText("" + psize);

    }


    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        // TODO add your handling code here:
        Rutinas.initDashboard(5);
        initpnJuego5(5);
        pnPrincipal.remove(pnInicio);
        pnPrincipal.add(pnJuego5);
        pnPrincipal.repaint();
        pnPrincipal.revalidate();
        int valueDas = 0;
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                valueDas = Rutinas.mostrarAyuda(i, j);
                System.out.print(" " + valueDas + " ");
            }
            System.out.println(" ");
        }
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed
        // TODO add your handling code here:
        Rutinas.initDashboard(8);
        initpnJuego5(8);
        pnPrincipal.remove(pnInicio);
        pnPrincipal.add(pnJuego5);
        pnPrincipal.repaint();
        pnPrincipal.revalidate();
        int valueDas = 0;
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                valueDas = Rutinas.mostrarAyuda(i, j);
                System.out.print(" " + valueDas + " ");
            }
            System.out.println(" ");
        }
    }//GEN-LAST:event_btnDificilActionPerformed
    private void buttonClicked(java.awt.event.MouseEvent click) {
        String btnName = "";

        elementsToShow.clear();
        JButton btn = null;
        //getting clicked button
        Object o = click.getSource();
        if (o instanceof JButton) {
            btn = (JButton) o;
        }

        if (btn != null) {
            btnName = btn.getName();
        }
        //left click or right click
        if (btn.isEnabled()) {
            if (SwingUtilities.isLeftMouseButton(click)) {
                int valueBehindButton = Rutinas.checkBackDashboard(btnName);
                if (valueBehindButton == 0) {
                    showNearZeroButton(btnName);
                }
                else if(valueBehindButton != 9){
                changeButton(btnName, valueBehindButton);              
                }
                else{
                // pierdo
                }


            } else if (SwingUtilities.isRightMouseButton(click)) {
                JOptionPane.showConfirmDialog(this, "click derecho");
            }
        }

    }

    private void showNearZeroButton(String pbtnName) {
        int row = 0, column = 0;
        row = Character.getNumericValue(pbtnName.charAt(1));
        column = Character.getNumericValue(pbtnName.charAt(2));
        Rutinas.spaceWithCero(row, column);
        elementsToShow = Rutinas.getListToShowCero();
        elementsToShowNumbers = Rutinas.getListToShowNumbers();
        for (String element : elementsToShow) {
            changeButton(element, 0);
        }
        for (String element : elementsToShowNumbers) {
            changeButton(element, 0);
        }
        Rutinas.cleanAllLists();
    }

    private void changeButton(String pName, int pvalor) {
        JButton btn;
        String imgName;
        btn = buttonMap.get(pName);
        imgName = chooseImage(0);
        btn.setIcon(getResizeImage(imgName));
        btn.setBackground(new java.awt.Color(255, 255, 255));
        btn.setEnabled(false);
        buttonMap.replace(pName, btn);
    }

    private String chooseImage(int pvalue) {
        String nameImage;
        if (pvalue == 9) {
            nameImage = "mina.png";
        } else {
            nameImage = pvalue + ".png";
        }
        return nameImage;
    }

    private ImageIcon getResizeImage(String imageName) {
        ImageIcon icoDefault = new ImageIcon(getClass().getResource("/buscaminasPackage/" + imageName));
        Image imageDefault = icoDefault.getImage();
        Image resizeImage = imageDefault.getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        ImageIcon resizeIcon = new ImageIcon(resizeImage);

        return resizeIcon;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDificil;
    private javax.swing.JButton btnNormal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSeleccionar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblquatity;
    private javax.swing.JPanel pnInicio;
    private javax.swing.JPanel pnJuego5;
    private javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
